---
- name: Loki
  become: true
  block:
    - name: Create a directory for loki
      ansible.builtin.file:
        path: "{{ monitoring_docker_working_directory_path }}/loki"
        owner: devops
        group: devops
        state: directory
        mode: '0755'

    - name: Create a storage directory for loki
      ansible.builtin.file:
        path: "{{ monitoring_docker_working_directory_path }}/loki/loki_storage"
        owner: devops
        group: devops
        state: directory
        mode: '0777'

    - name: Копирование конфигурационного файла loki
      ansible.builtin.template:
        src: "local-config.yaml.loki.j2"
        dest: "{{ monitoring_docker_working_directory_path }}/loki/local-config.yaml"
        mode: '0644'

    - name: Run Loki container
      docker_container:
        name: loki
        image: "grafana/loki:{{ monitoring_loki_version }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ monitoring_loki_port }}:3100"
        volumes:
          - "{{ monitoring_docker_working_directory_path }}/loki/local-config.yaml:/etc/loki/local-config.yaml"
          - "{{ monitoring_docker_working_directory_path }}/loki/loki_storage:/tmp/loki"
