---
- name: Создание пользователя devops
  become: true
  block:
    - name: Создание пользователя
      ansible.builtin.user:
        name: devops
        groups: docker
        password: "{{ monitoring_devops_password }}"
        create_home: true
        shell: /bin/bash
