---
- name: Проверка синтаксиса Nginx
  become: true
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false

- name: Перезапуск Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
