services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.110.0
    container_name: victoria-metrics
    ports:
      - "192.168.1.110:8428:8428"
    #command: >
    #  /victoria-metrics
    #  -retentionPeriod=1
    #  -httpListenAddr=:8428
    #  -storageDataPath=/storage
    volumes:
      - victoria-metrics-data:/storage

volumes:
  victoria-metrics-data: