---
- name: Создание nginx site php-fpm
  become: true
  block:
      # - name: Install PHP-FPM
      #   apt:
      #     name: php-fpm
      #     state: present

      - name: "Создание директории /var/www/{{ domain }}"
        ansible.builtin.file:
            path: "/var/www/{{ domain }}/php"
            state: directory
            mode: '0755'

      - name: "Создание индекс php страницы для {{ domain }}"
        ansible.builtin.template:
            src: php-www-index.php.j2
            dest: "/var/www/{{ domain }}/php/index.php"
            mode: '0644'

      - name: Копирование конфигурационного файла Nginx
        ansible.builtin.template:
            src: php_fpm-conf.j2
            dest: "/etc/nginx/sites-available/{{ domain }}"
            mode: '0644'

      - name: Создание символической ссылки
        ansible.builtin.file:
            src: "/etc/nginx/sites-available/{{ domain }}"
            dest: "/etc/nginx/sites-enabled/{{ domain }}"
            state: link
        notify:
            - Проверка синтаксиса Nginx
            - Перезапуск Nginx

      - name: Start php8.3-fpm service
        ansible.builtin.service:
            name: php8.3-fpm
            state: restarted
