---
- name: Получение SSL сертификата
  become: true
  block:
      - name: Копирование сертификата
        ansible.builtin.template:
            src: certificate.crt
            dest: "{{ nginx_ssl_crt_path }}{{ domain }}.crt"
            mode: '0644'

      - name: Копирование ключа для сертификата
        ansible.builtin.template:
            src: certificate.key
            dest: "{{ nginx_ssl_key_path }}{{ domain }}.key"
            mode: '0644'

      - name: Копирование конфигурационного файла Nginx
        ansible.builtin.template:
            src: nginx_https_site.conf.j2
            dest: "/etc/nginx/sites-available/{{ domain }}"
            mode: '0644'

      - name: Создание символической ссылки
        ansible.builtin.file:
            src: "/etc/nginx/sites-available/{{ domain }}"
            dest: "/etc/nginx/sites-enabled/{{ domain }}"
            state: link

      - name: Проверить и перезапустить nginx
        ansible.builtin.debug:
            msg: "Проверка синтаксиса Nginx и Перезапуск Nginx"
        changed_when: true
        notify:
            - Проверка синтаксиса Nginx
            - Перезапуск Nginx
