---
- name: Создание нового ресурса Nginx
  become: true
  block:
      # - name: Создание пользователя '{{ domain }}' с домашней директорией
      #   ansible.builtin.user:
      #       name: "{{ domain }}"
      #       create_home: true

      - name: Копирование конфигурационного файла Nginx
        ansible.builtin.template:
            src: site_config.conf.j2
            dest: "/etc/nginx/sites-available/{{ domain }}"
            mode: '0644'
        notify:
            - Проверка синтаксиса Nginx
            - Перезапуск Nginx

      - name: Создание символической ссылки
        ansible.builtin.file:
            src: "/etc/nginx/sites-available/{{ domain }}"
            dest: "/etc/nginx/sites-enabled/{{ domain }}"
            state: link
