---
- name: Nginx
  ansible.builtin.import_tasks:
    file: install.yml
# - import_tasks: start.yml
# - import_tasks: config.yml

# - name: Копирование конфигурационного файла
#   template:
#     src: nginx.conf.j2
#     dest: /etc/nginx/sites-available/default
#   notify: Перезапуск Nginx

# - name: Создание символической ссылки в sites-enabled
#   command: ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#   args:
#     removes: /etc/nginx/sites-enabled/default
#   notify: Перезапуск Nginx
