---
- name: Site
  hosts: ["new_site_mm-prod"]
  gather_facts: true
  tasks:
    - name: Запуск роли
      ansible.builtin.include_role:
        name: docker
        tasks_from: install.yml

    - name: Запуск роли
      ansible.builtin.include_role:
        name: docker
        tasks_from: init_docker_home.yml
