---
- name: Site
  hosts: customer-dsp-prod
  tasks:
    - name: Запуск роли
      ansible.builtin.include_role:
        name: docker
        tasks_from: install.yml
        # handlers_from: main.yml
