---
- name: Создание SSL сертификата
  block:
      - name: Проверка создания сертификата
        become: true
        ansible.builtin.shell:
            cmd: |
              set -o pipefail
              {% if certbot_wildcart_domain %}
                sudo certbot certonly --dry-run --nginx -d "*.{{ domain }}" -d "{{ domain }}"
              {% else %}
                sudo certbot certonly --dry-run --nginx -d "{{ domain }}" -d "www.{{ domain }}"
              {% endif %}
            executable: /bin/bash
        changed_when: false
        register: certbot_test_output

      - name: Вывести результат выполнения контейнера
        ansible.builtin.debug:
            msg: "{{ certbot_test_output }}"
